apiVersion: v1
kind: Pod
metadata:
  name: my-flask-app
spec:
  containers:
  - name: my-flask-app
    image: ghcr.io/emmanuelogiji/cloudboosta-flask-app:0.1.0
    ports:
    - containerPort: 9900
    volumeMounts:
      - name: config-volume
        mountPath: /app/templates/
    envFrom:
    - configMapRef:
        name: flask-config
    env:
    - name: AUTHOR
      valueFrom:
        secretKeyRef:
          name: flask-secret
          key: AUTHOR_NAME
    startupProbe:
      httpGet:
        path: /author
        port: 9900
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 9900
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 9900
      initialDelaySeconds: 15
      periodSeconds: 20
  volumes:
    - name: config-volume
      configMap:
        name: mount-config